// WebClientAngular/src/app/auth/auth.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { SignalRService } from 'src/app/services/signalr.service';
import { LocalStorageService } from 'src/app/services/local-storage.service';
import Config from 'src/config';
import Utils from 'src/utils';

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.css'],
  providers: [{ provide: SignalRService }]
})
export class AuthComponent implements OnInit {

  clientId: string = Utils.getClientId();
  @Input()  login: string = "vinge";
  @Input()  password: string = "12345";

  constructor(
    private router: Router,
    private signalr: SignalRService,
    private localStorage: LocalStorageService,
    private httpClient: HttpClient) {
  }

  ngOnInit(): void {
    var self = this;
    self.onLoginResponse();
  }

  onLoginResponse(): void {
    var self = this;
    self.signalr.addHandler("LoginResponse", function (response) {
      if (!response || !response.success) {
        self.router.navigate(['/']);
      } else {
        self.localStorage.setAuthData({ login: self.login, token: response.token, clientId: self.clientId });
        self.router.navigate(['/photos']);
      }
    });
    self.signalr.start(self.clientId);
  }

  sendAuth(): void {
    var self = this;
    var postData = { login: self.login, password: self.password, clientId: self.clientId };
    self.httpClient.post(Config.loginApiPath, postData).toPromise();
  }
}

<div class="root">
    <div class="welcome">
        <span>{{ locale.authWelcome }}</span>
    </div>
    <div class="container">
        <div class="login-container">
            <div class="login-label"><label>{{ locale.authLogin }}</label></div>
            <div class="login-input">
                <input type="text" [value]="login" (input)="login = $event.target.value" />
            </div>
        </div>
        <div class="password-container">
            <div class="password-label"><label>{{ locale.authPassword }}</label></div>
            <div class="password-input">
                <input type="password" [value]="password" (input)="password = $event.target.value" />
            </div>
        </div>
        <div class="send"><button (click)="sendAuth()">{{ locale.authSend }}</button></div>
    </div>
    <div class="error" [class.error-hide]="hasError == false"><span>{{ locale.authLoginError }}</span></div>
</div>

// WebClientVueJs/src/components/Auth.vue
<template>
    <div class="auth">
        <div>
            <label>Login: </label>
            <input type="text" v-model="login" />
        </div>
        <div>
            <label>Password: </label>
            <input type="password" v-model="password" />
        </div>
        <button v-on:click="send">Send</button>
    </div>
</template>

<script>
    import Axios from 'axios';
    import Config from '@/config';
    import '@/cookies';
    import SignalR from '@/signalr';
    import Utils from '@/utils';

    export default {
        name: 'Auth',
        data() {
            return {
                login: "vinge",
                password: "12345"
            };
        },
        mounted() {
            var self = this;
            self.clientId = Utils.getClientId();
            SignalR.start(self.clientId);
            SignalR.connection.on("LoginResponse", function (response) {
                if (response.success) {
                    self.$cookies.set('login', self.login);
                    self.$cookies.set('token', response.token);
                    self.$router.push('photos');
                }
            });
        },
        methods: {
            send() {
                Axios({
                    method: 'post',
                    url: Config.loginApiPath,
                    data: { clientId: this.clientId, login: this.login, password: this.password }
                });
            }
        }
    };
</script>

<style scoped>
</style>
