// WebClientAngular/src/app/upload-photo/upload-photo.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { LocalStorageService } from 'src/app/services/local-storage.service';
import Config from 'src/config';
import Utils from 'src/utils';

@Component({
  selector: 'app-upload-photo',
  templateUrl: './upload-photo.component.html',
  styleUrls: ['./upload-photo.component.css']
})
export class UploadPhotoComponent implements OnInit {

  files: FileList

  constructor(
    private localStorage: LocalStorageService,
    private httpClient: HttpClient
  ) { }

  ngOnInit(): void {
  }

  handleFilesUpload(files: FileList): void {
    var self = this;
    self.files = files;
  }

  submitFiles(): void {
    var self = this;
    var authData = self.localStorage.getAuthData();
    var uploadFunc = function (filesBase64) {
      var postData = { login: authData.login, token: authData.token, clientId: authData.clientId, files: filesBase64 };
      self.httpClient.post(Config.uploadPhotosApiPath, postData).toPromise();
    };
    Utils.filesToBase64(self.files, uploadFunc);
  }
}

<div>
  <label>
    Upload photos:
    <input type="file" id="files" ref="files" multiple (change)="handleFilesUpload($event.target.files)" />
  </label>
  <button (click)="submitFiles()">Send</button>
</div>

// WebClientVueJs/src/components/UploadPhoto.vue
<template>
    <div>
        <label>
            Upload photos:
            <input type="file" id="files" ref="files" multiple v-on:change="handleFilesUpload()" />
        </label>
        <button v-on:click="submitFiles()">Send</button>
    </div>
</template>

<script>
    import Axios from 'axios';
    import Config from '@/config';
    import '@/cookies';
    import Utils from '@/utils';

    export default {
        data() {
            return {
                clientId: "123213123123",
                files: []
            }
        },
        methods: {
            handleFilesUpload() {
                this.files = this.$refs.files.files;
            },
            submitFiles() {
                var self = this;
                var uploadFunc = function (filesBase64) {
                    Axios({
                        method: 'post',
                        url: Config.uploadPhotosApiPath,
                        data: { clientId: self.clientId, login: self.$cookies.get('login'), token: self.$cookies.get('token'), files: filesBase64 }
                    });
                };
                Utils.filesToBase64(this.files, uploadFunc);
            }
        }
    }
</script>

<style scoped>
</style>
